# Site settings
title: "Mohammed Nawaz"
description: "This is my blog"
baseurl: ""
url: "http://mdnnawaz.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "about"
    url: /about
  - title: "git"
    url: http://github.com/mdnnawaz
